trigger: none # We only want to trigger manually or based on resources
pr: none

resources:
  pipelines:
  - pipeline: CI
    source: ImageHash.Build
    trigger:
      tags:
      - auto-release

stages:
- stage: GitHubRelease
  displayName: GitHub Release
  jobs:
  - deployment: create
    pool:
      vmImage: ubuntu-latest
    environment: No-Approval
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - powershell: |
              Write-Host "##vso[build.updatebuildnumber]$(resources.pipeline.CI.runName)"
            displayName: Set pipeline name
          - task: GitHubRelease@1
            displayName: GitHub release (create)
            inputs:
              gitHubConnection: github_coenm_pan
              repositoryName: $(Build.Repository.Name)
              target: $(resources.pipeline.CI.sourceCommit)
              tagSource: userSpecifiedTag
              tag: v$(resources.pipeline.CI.runName)
              title: v$(resources.pipeline.CI.runName)
              isDraft: true
              changeLogCompareToRelease: lastNonDraftRelease
              changeLogType: issueBased
              changeLogLabels: |
                [
                  { "label" : "bug", "displayName" : "Fixes", "state" : "closed" },
                  { "label" : "enhancement", "displayName": "Enhancements", "state" : "closed" }
                ]

- stage: nuget_org
  displayName: nuget.org
  dependsOn: GitHubRelease
  jobs:
  - deployment: push
    pool:
      vmImage: ubuntu-latest
    environment: No-Approval
    strategy:
      runOnce:
        deploy:
          steps:
          - download: CI
            artifact: packages
            displayName: Download nuget packages artifact
            patterns: 'packages/*'
          - task: NuGetToolInstaller@1
            displayName: Use NuGet 5.x
            inputs:
              versionSpec: 5.x
          - task: NuGetCommand@2
            displayName: NuGet push nupkg
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/CI/packages/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: nuget.org     